name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunt-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 


      - name: Execute Python Script
        run: |
          python my.py
